### ISSUE TITLE
Add option to show window titles in tasks buttons

### ISSUE THREAD

**Issue by kilbith** [jderose9/dash-to-panel#115]
Thanks you very much for your work. The title says it all.

**Comment by jderose9** [comment]
Hi there! Could you explain what you mean by "tasks buttons"? I'm not sure which buttons you are referring to. Thanks!

**Comment by kilbith** [comment]
The buttons to switch between windows. There's currently just an icon inside.

**Comment by dziku1337** [comment]
I'm pretty sure he means this:
![taskbar](https://cloud.githubusercontent.com/assets/11319008/24831437/97185b38-1c99-11e7-8b16-66f8313faf3d.png)

**Comment by jderose9** [comment]
So only running applications get text and the window title is displayed rather than the application name? And you just truncate it if it's too wide?

**Comment by kilbith** [comment]
No, just truncate them if it's too wide.

**Comment by jderose9** [comment]
@kilbith 
>No, just truncate them if it's too wide.

I'm sorry, I don't understand this comment. Do you disagree with my explanation of how the feature should work? Thanks!

**Comment by kilbith** [comment]
Yes, I agree with your explanation. To put it simple, do it exactly like the Windows 10 bar, with exactly the same options.

**Comment by jderose9** [comment]
@kilbith I just found this feature in Windows. It appears that it creates additional instances of the icon when multiple windows are open (but, only if there is room to do so). Is this the desired behavior?

**Comment by kilbith** [comment]
Hodor.

**Comment by mcapu** [comment]
Are there plans to add this? It would be a great addition, in my opinion.

**Comment by TurkeyMan** [comment]
I'd really love this too. Windows taskbar has some nice configuration this way, and I'm sure everyone will prefer the settings slightly different, I suggest to follow windows lead with configuration, since that's what people who are asking for this are familiar with.
You asked before about button width when text is visible; in windows, the buttons have a constant maximum width, and they uniformly shrink to fit if there is not enough space in the panel.
You also asked about additional instances of the buttons, I also prefer the way windows shows multiple buttons for each running instance of apps that are joined together. If you rearrange the panel, all instances move together as one object, even though it shows one button for each app instance.

**Comment by TurkeyMan** [comment]
For what it's worth, if you implement this, I think it will be perfect for windows users to feel comfortable, which is really great for users who are new to linux like many staff in my office. I'll definitely recommend to all of them.

**Comment by secretfork** [comment]
I wish there was an option to vote for issues that need attention, instead of having to do a "me too". But here we go. I'd very much like this as an option, and i agree the way windows does it is (almost) just perfect.

Also, i'd argue this will not only benefit windows users. This is how gnome used to do it. This is how kde does it. This is how xfce used to do it. I still configure window 7 and 10 this way. So i figure it will apeal to quite a few users out there.

Having said that, i'd prefer if opened _windows_ stay in their own space (or partition) of the panel, so as to not mix with _applications (launchers)_. So, _applications (launchers)_ to the left, and when they get clicked and open a _window_ the _window_ button should go to the right of application launchers. As you can see, this is not the case in the screenshot from dziku1337 above. I'd argue this is the only thing windows got "wrong". But maybe this is just me.

There is one more aspect to this. The "smart" launcher disappears when you open up a new window. This is how kde and windows does it. The old way was to have static launchers that didn't disappear just because you launched the application (think "quick start" in windows xp, or application shortcuts on the panel in gnome 2/xfce). Which one of the two behaviors is preferred i don't know. Maybe the more modern way will appeal to more users (smart launchers).

**Comment by voidray** [comment]
Regarding the order: For me the advantage in Windows is that the list of windows has always the same order in the taskbar. In KDE (and other DE) the order is the one in which you opened the files. If they are always in the same order it is easier / quicker to find the right window.

Regarding "mixing" icons with open windows (mentioned secretforks last comment): If there would be an option to switch between the windows and the kde behavior it would be even better (more flexible) than in Windows.

**Comment by charlesg99** [comment]
Hi, I'll have a hack at this since I also really want this feature. See #208

**Comment by jderose9** [comment]
Thanks so much for the great work, @charlesg99. This is very much appreciated!!
