### ISSUE TITLE
Configuration windows are too big

### ISSUE THREAD

**Issue by kilbith** [jderose9/dash-to-panel#119]
... and I can't access the settings at bottom.

![capture d ecran de 2017-04-09 12-23-56](https://cloud.githubusercontent.com/assets/7883281/24836580/8718104e-1d1f-11e7-8e69-721e44e686a2.png)

**Comment by bil-elmoussaoui** [comment]
@jderose9 I can create a PR and use a Gtk.ScrolledWindow? Which will fix this issue :)

**Comment by jderose9** [comment]
@bil-elmoussaoui That would be awesome! Thanks so much.

**Comment by jderose9** [comment]
@bil-elmoussaoui I merged in your PR, but I thought it would be better if the tab contents could scroll so the tabs stayed at the top even after scrolling down. Of course, I couldn't get that working. I also thought it was a little weird that the scrolled window opened so small on my larger screen, so I wanted it to default to as large of a size as would fit the screen. That doesn't really seem to be possible either.

I ended up adjusting it so that the scrolled window size is set to the full height of the window if the monitor size allows, otherwise it will open at the default smaller size with scrollbars displayed. It's kind of disappointing though because when the height of the windows is manually set, it can never be resized smaller by the user - only larger.

Anyway, if you know of any way to improve on this, feedback would be appreciated. Thanks!

**Comment by bil-elmoussaoui** [comment]
Well, all of what you've mentioned are the limits of gnome shell extensions; I tried creating a Gtk.Window and move to using a Gtk.Stack with a Gtk.StackSwitcher but doesn't seem to be possible, as whenever you open the settings another default window will be opened; as by default Gnome Shell will get the widget returned by the user and add it in a Gtk.Window...
I've also tried to use a Gtk.ScrolledWindow inside the Gtk.Notebook but doesn't work either; I can't set the width of the settings window neither :( 

A better solution would be using Gtk.Revealer, and have different sub-categories for each tab, whenever you click on a category the rest will be hidden and only the one you clicked on will be shown, but again, this should be reported upstream and as soon as it "works" fine for the users, you really shouldn't spend your time trying to fix what you shouldn't even think about !
