### ISSUE TITLE
Dash to Panel is 'Incompatible' with GNOME 3.14.4

### ISSUE THREAD

**Issue by joby-m** [jderose9/dash-to-panel#134]
When trying to install the extension with the given, link I am unable to because the install button says 'Incompatible'. I also tried building from source but i am unable to enable the plugin in Gnome Tweak Tool.

`debian:~$ gnome-shell --version
GNOME Shell 3.14.4
`

**Comment by AravK** [comment]
README states that it's been tested with Gnome 3.18+
You might need to move your repositories onto testing to get gnome 3.18+

**Comment by jderose9** [comment]
I believe @franglais125 has said it doesn't work and that doing so would be a rather large amount of work. :( Given the age of 3.14 it probably won't realistically get done.

If you want to try yourself, open the extension folder and edit the metadata.json to include 3.14. Just be aware it can cause gnome-shell to crash on start and you will have to switch to another command line terminal and remove the extension folder.

**Comment by franglais125** [comment]
Indeed, there are a few features that just don't work on gnome < 3.18.

@joby-m Please don't take this as self-promotion, it's simply a suggestion. I was using Debian Jessie as well, with dash-to-dock and I backported some of the latest features to 3.14. Number hotkeys, multi-monitor, etc.

This is the branch I was running: https://github.com/franglais125/dash-to-dock/tree/gnome-3.14-custom

Please note that I don't maintain it anymore, since I jumped to Debian 9. But it was working great for me.
