### ISSUE TITLE
RHEL 7 (GNOME 3.14) Support

### ISSUE THREAD

**Issue by igaldino** [jderose9/dash-to-panel#141]
Hi man, nice job.

@ work I need to use RHEL 7, which uses GNOME 3.14. Are you able to make it compatible with that version?

Thanks.

**Comment by jderose9** [comment]
Hello! I believe @franglais125 looked into this a bit and felt that it was a rather large effort due to drastic changes made after 3.14. I'll leave this open though in case someone gets time to dig into it further.

**Comment by franglais125** [comment]
What distributions are left using 3.14?
- RHEL7
- Debian 8
- Scientific Linux perhaps?
- CentOS?

I don't know how much effort this would be, and if it would be worth it or not. One thing is for sure, simply adding "3.14" to the metadata is not enough, as there are features that are not supported. For instance, @micheleg kept separate branches for 3.14 and 3.16 for dash-to-dock.

I can try and see what things we would need to remove, and perhaps we can simply keep a separate branch for older versions of Gnome. But I don't promise anything soon. These days I am bit busier!

**Comment by micheleg** [comment]
I used to keep separated branches for all GNOME Shell versions, regardless of the number of changes required. This was because in the _old days_ lots of things were changing upstream from version to version. For the bits shared with [dash-to-dock](https://github.com/micheleg/dash-to-dock/), you can find the most relevant changes from 3.14 to 3.16 just after I enabled 3.16 (from https://github.com/micheleg/dash-to-dock/commit/226234decd0b8665a68b8b87f1962145ccdfe25d). Not sure it's worth putting effort in it. I tried to backport new features  to 3.14 (with @franglais125 help), and although I'm still using that version at work, I eventually gave up when I updated my developing machine.

**Comment by hubslave** [comment]
I think this is not necessary anymore since RHEL updated Gnome-Shell to 3.22 in 7.4 release

**Comment by hubslave** [comment]
Also Debian 9 uses 3.22, Centos and Scientific Linux inherited Gnome 3.22 from RHEL 7.4 so there is probably no more distribution left behind

**Comment by igaldino** [comment]
I agree, burn this request out!
