### ISSUE TITLE
Incorporate TopIcons Plus' functionality

### ISSUE THREAD

**Issue by andrebrait** [jderose9/dash-to-panel#152]
It's just an idea, but since the legacy tray icons area doesn't really make sense with this extension, would it be possible to do what TopIcons Plus does by default?

Even if you choose not to do it, is it at least possible (for research purposes)?

**Comment by jderose9** [comment]
I don't really get point of the legacy tray period :)

I understand the desire to have features that most users will find desirable neatly packaged into a single extension.

That said, I don't really want to incorporate Top Icons Plus into this extension. When new features/config options are added, they will have to be ported in. When gnome-shell releases a new version with breaking changes, this extension would have to either fix the issues or wait to release a compatible version until top icons plus is fixed and ported over. Since that stuff will take time from working on new enhancements, I think it is better to not maintain duplicated code.

Thanks for your ideas!
