### ISSUE TITLE
Bug when changing panel size 

### ISSUE THREAD

**Issue by sw9** [jderose9/dash-to-panel#202]
When you increase the panel size (to say 96) and bring it back down to 24 again, the spacing between the icons increases. The app numbering that temporarily show up also stays too high.

Before:
![](http://i.imgur.com/vIs7824.png)

After:
![](http://i.imgur.com/2NruUBd.png)
![](http://i.imgur.com/97XG3KJ.png)

Also, I noticed that there still exists some margin between app icons at small icon sizes even when it's set to 0. You can see this in the before image. Not sure if it's a bug or intended behavior though.

**Comment by jderose9** [comment]
Hi! Thanks for this. I believe it was already reported here though as #102. Please hop over there for updates.

Regarding the margin at 0 - I think you are referring to the padding (ie inside the shaded area on hover/selection) which is variable depending on the height of the panel. The reason is that the icons are scaled in increments based on the standard icon sizes provided with most icon themes. So if you make the panel a height such as that, say, a 24px square icon will be the largest that can fit, any extra space will be filled with padding. You can eliminate some of this by making the panel height slightly lower before it bumps down to the next icon size. There's also a few pixels padding to allow for the running indicator. There's an existing issue #75 to allow more control over this.
