### ISSUE TITLE
When will be release in extensions.gnome.org?

### ISSUE THREAD

**Issue by AlexGluck** [jderose9/dash-to-panel#234]
I wait russian translation, but month later release not happen. If i install extension from github i can't control extension update in automatical mode.

**Comment by jderose9** [comment]
Thank you very much for your contribution! I tend to wait until there is a big new feature or a handful of bug fixes, and there hasn't been much going on over the summer. I expect there will be some more development soon. I will start to notify translators ahead of time so that they can update any new changes before release.
