### ISSUE TITLE
Feature Request: change behavior for left-click and drag icon of the panel

### ISSUE THREAD

**Issue by mispp** [jderose9/dash-to-panel#248]
Assumption: panel is on the bottom on the screen
- To replicate the behavior in windows - left click and drag 'up' would actually fade in open windows for that application.
- Currently you'd remove it from favorites.

This doesn't mean that you can't move it left-right to change the order, just to prevent using left-click to remove it from favorites.

**Comment by jderose9** [comment]
Hello! I'm sorry, I'm not able to reproduce the left-click causing an item to be removed from favorites in this extension. I'm also not able to reproduce the windows fading in on Windows 10, unless you mean the window preview popup?

**Comment by mispp** [comment]
1. "left-click causing an item to be removed from favorites" - you're right, now i'm thinking if my memory serves me right... maybe i mixed it with dash to dock. Anyway - is it possible to contain the icon in the panel by only allowing it to be dragged left-right (now if you drag it off, it comes flying back to panel)? in this case, the second point would make sense

2. "windows fading in on Windows 10" - yes, the windows preview popup like [here](https://cdn.ghacks.net/wp-content/uploads/2015/09/disable-taskbar-previews-windows-10.jpg). In windows 7 if you drag the icon and move it up, the preview popup fades-in with transparency being proportional on how far up did you move the mouse. The icon stays put.

**Comment by jderose9** [comment]
Windows 7 might have faded with the mouse drag, but I couldn't see this on Windows 10 (left-click dragging just opens the right click context menu).

At any rate, I would like to leave the behavior how it is. The reason is that when dragging off of the panel, the application become a drag-and-drop source, so you can do things such as drag the icon onto the overview (when opened) and have it launch an instance on that monitor.

Thanks very much for the suggestion and your time, though!
