### ISSUE TITLE
Can we have a roadmap of the enhancements?

### ISSUE THREAD

**Issue by Lucapz** [jderose9/dash-to-panel#264]
jderose9 can we have a roadmap of the enhancements so we all know what is going on?

Example of a great idea from 3 months ago:
github.com/jderose9/dash-to-panel/issues/208

We have no idea if enhancements like the one above have been looked at , being worked on or have been dropped?

The original poster asked for an update and got ignored but with a roadmap people wouldn't need to ask and we wouldn't need to keep re-checking threads for any changes?

Thanks 👍

**Comment by lexruee** [comment]
@Lucapz 
I really like this idea. For example, the Arc-Menu project has created a nice roadmap for their extension: https://github.com/LinxGem33/Arc-Menu/issues/42

Maybe, we could adapt something similar to that, so we know the direction of this project.

**Comment by Lucapz** [comment]
@lexruee 

That's the perfect example and exactly what i meant.  :)

Thanks

**Comment by jderose9** [comment]
There's not exactly a roadmap, as I don't really know what will be worked on next. The items that get completed are the ones that wonderful people volunteer their time complete.

In terms of my personal contributions to the extension, my priorities have been:

1) Address critical bugs or compatibility issues caused by new gnome releases
2) Review/merge pull requests as quickly as I can.
3) Try to keep the issues list as clean as possible. Close dupes, determine if bugs are really caused by the extension, evaluate whether requests really make sense to live in an icon-based taskbar extension, clarify confusing descriptions, etc. This way if someone else comes along and wants to work on something, they can find things easily. (Admittedly I am a bit behind on this at the moment).

When I get through these things, I try to pick up items from the open issues - but, I'm not someone with loads of extra free time, and it tends to come in spurts.

Once I've reviewed issues, if I can determine that it makes sense to implement and that we have enough information to do so, I label it (bug, enhancement, etc). So, I will definitely accept working pull requests for any labelled issues.

To specifically address the issue that you mentioned - The reason that there's no news on it is just that nobody has come along and felt compelled to volunteer their time toward it.

I'm definitely open to improving the process, so if you have other ideas feel free to pitch them!

**Comment by Rase1959** [comment]
Unless you point out what enhancements you want added , what ones you don't want and what ones you need help with then how is anyone supposed to know or volunteer ?

That's the point Lucapz was making that no one knows anything , it wasn't an extra demand on you.

We are all left in the dark as to what direction this project is going in and no one is going to waste time adding code for you to say weeks or months later that no it doesn't fit with your project or works with any code you may have already worked on in private.

help us to help you.

**Comment by LinxGem33** [comment]
@jderose9 

firstly we really appreciate your work on this extension its very welcome in the community, and regarding this issue some of us on the Arc menu team have been discussing contributing to your project (including myself) as we would like to see this project move forward and get a bit more developer love :) ...as we understand things can be a bit overwhelming when running a project by yourself and in that spirit we are ready to help the best we can if your open to that, you already have one of the team contributing at the moment @lexruee 

i can assist with any digital art and bugs and some small code refinements as i currently run multiple projects and contribut to others and some of the other team can assist with the more pressing code refinements or problems you may have or just need a second pair of eyes etc... 

regarding this issue and setting up a roadmap if you let me know what features you want to see in dash to panel we can start to build a roadmap which will allow other developers to contribute to that feature please see my roadmap as a [example](https://github.com/LinxGem33/Arc-Menu/issues/191) 

i look forward to your response

kind regards - *LinxGem33*

**Comment by jderose9** [comment]
@Rase1959 - 

Any of the issues labeled "enhancement" or "bug" have been vetted and approved. I'll merge a reasonable solution to any of those issues. This probably needs to be communicated more clearly. If you want to post in the issue that you are working on it, I can mark it as "In Progress" to avoid duplicating effort. If you are unsure of anything, or need help picking an item to work on, just ask.

@LinxGem33 -

I'm very excited that you would like to help!

The README could definitely use some help visually (and Arc Menu's look awesome!).

I see your developer wiki is still a work-in-progress but maybe that is something we could work on together to help get more people on board - the learning curve to working on gnome extensions is definitely a blocker for a lot of people (and maybe the best solution is just to contribute to the official gnome wiki).

At this time I'd prefer to use the issues list to track enhancements individually, rather than a single issue with a grid, so that the discussions on each item aren't intermingled and to not feel too rigid regarding future direction or contributions. But, we can make the the issue labels clearer and some contribution guidelines could be provided in the readme or wiki.

How do you feel about hopping on slack or irc to chat in more detail about some of these things? (How do you guys communicate about Arc Menu?)

**Comment by LinxGem33** [comment]
@jderose9  

hey regarding updating the README.md ill get started on that straight away ill design the art work and if you want a new logo ill design that to.. ill release all art work under a GPL v3 licence 

regarding how we communicate we have found **"Wire"** to be quite good as we can share prototype artwork UML diagrams for architecture development `etc for illustration and also its open source we also use the irc if we want to find out more regarding gnome development ... if you want to open an account on wire and send your user or ill give you mine we can get started :)

**Comment by lexruee** [comment]
Regarding communication, [gitter](https://gitter.im) seems to be a nice communication platform for developers that use github. @LinxGem33 I don't think that wire is an ideal for more than two people 🙂 or a community.

**Comment by jderose9** [comment]
I've created a gitter room for anyone that wants to hop in:
https://gitter.im/dash-to-panel/Lobby

**Comment by jderose9** [comment]
In addition to the awesome design work @LinxGem33 has done, I've been going through and tagging items as "help wanted" and "high priority". Feel free to grab any of those. I've also started a wiki page with the high priority items and will start to flesh out some more instructions on getting started: https://github.com/jderose9/dash-to-panel/wiki/Contributing
