### ISSUE TITLE
Cant add Netbeans to favorites list

### ISSUE THREAD

**Issue by thachngopl** [jderose9/dash-to-panel#303]
It would be nice if dash-to-panel supports this.
Thank you

**Comment by bil-elmoussaoui** [comment]
It's due to a missing StartupWMClass entry in the desktop file of Netbeans. You should be able to fix it with something like this
https://github.com/bil-elmoussaoui/StartupWMClassFixer

Netbeans might not be supported yet, but you can take a look at the README which explains how to do that manually.

**Comment by thachngopl** [comment]
Thank you :+1:
