### ISSUE TITLE
Add Intellihide behavior to panel

### ISSUE THREAD

**Issue by deikatsuo** [jderose9/dash-to-panel#41]
https://youtu.be/KBPtrzfvMNY
Compatibility with 'Hide topbar'

**Comment by jderose9** [comment]
I thought that I had tested this and it was working, but I just tried and I guess not. This behavior may make sense to pull in as part of this extension since it will need to account for the bottom positioning of the bar and sync with the preview window state. (I'm updating your title, hope you don't mind)

**Comment by PHLAK** [comment]
Is there any ETA on this feature yet?  Auto/inteli-hide is the only feature currently missing that I really desire.

**Comment by jderose9** [comment]
@PHLAK I'll be working on multi-monitor support next and I don't think anyone else is working on it, so not really... If someone wants to take a crack at it I'll be happy to help get them started.

**Comment by adtac** [comment]
@jderose9 Hey. I'll try to take a stab at this. Brilliant extension and this feature would make it infinitely better. But I also have zero experience with GNOME extensions, so don't hold your breath ;)

**Comment by emielmolenaar** [comment]
This feature would be really really really awesome!

**Comment by vivaeltopo** [comment]
yes! Please add auto hide functionality!

**Comment by emielmolenaar** [comment]
Is it this simple? 

https://github.com/dimka665/hide-top-panel/blob/master/hide-top-panel%40dimka665.gmail.com/extension.js

I have no experience in writing Gnome extensions, but I write Javascript kind of daily. If the code above should do the trick somehow (I can imagine some tweaks are needed) I am willing to try to fix this in some spare time :smiley:

**Comment by jderose9** [comment]
@emielmolenaar I think it will be more complicated, but if you already know javascript I think you should give it a shot :)

The extension you linked removes the top bar permanently, while we need to show it again when the user navigates their mouse towards the edge of the screen. The behavior should mostly be in dash-to-dock already, so mostly you will need to show/hide the gnome main panel rather than the dock.
https://github.com/micheleg/dash-to-dock/blob/master/intellihide.js

The main thing I was worried about was possibly having the panel snap close when you navigated into the window preview popup, but I believe this feature was now added to dash-to-dock by @franglais125 so this might be handled already.

The similarly named Hide-Top-Bar also uses the dash-to-dock intellihide code and applies it to the main panel. You can check out that code or maybe just fix whatever bug is occurring in that extension:
https://github.com/mlutfy/hidetopbar

**Comment by emielmolenaar** [comment]
Thanks for replying, jderose9! Actually, https://github.com/mlutfy/hidetopbar works pretty well. I'll keep it around for a few days, let's see how it holds :smiley:

**Comment by Nebrit** [comment]
Please develop auto-hide in top and in bottom position as native option of Dash to panel, the new users that we lost unity in 17.10 we need this option to have a perfect extension. If you develop you will have more users.

**Comment by jasiralavi** [comment]
That would be great! Currently using HideTopBar for now. 
But if i'm using the DTP with the panel at the bottom, the HTB thinks that the panel on top and reveals only when the mouse touches the top edge. Then it requires an enable-disable to work correctly... until the next reboot.

**Comment by daledavies** [comment]
Definitely would love to see this feature, it would make this pretty much feature complete from my perspective. I too use HideTopBar but it does occasionally think the bar is still stuck to the top of the screen.

**Comment by charlesg99** [comment]
I'll give it a shot! Somebody already working on this?

**Comment by charlesg99** [comment]
I'm looking for some feedback as to which settings would be relevant. Here is what I have working so far:

![image](https://user-images.githubusercontent.com/33044886/37190584-47d745aa-2320-11e8-8283-88c12f2ec227.png)

The panel can hide from Focused windows, All windows and Maximised windows.

Any thoughts?

**Comment by franglais125** [comment]
That's great :). Here is some feedback, based on the dash-to-dock settings:

1. What about full screen apps? I.e. Say I push `F11` on Firefox and want to access the panel.
2. Perhaps an option for pressure to show? I.e. how much do I need to push on the screen border for the panel to show.

**Comment by charlesg99** [comment]
Hey @franglais125, thanks for your input. I will add an option to allow the reveal of the panel when apps are full screen, very good idea. As for the pressure to show, I don't understand as I already included some settings for this (my description might need some tweaking). Could you please elaborate on what you would add?

**Comment by franglais125** [comment]
Re-salut @charlesg99 ! Sorry for the confusion, I was in fact quite tired when I wrote the last message.

Indeed, you have already included the pressure settings. I can't believe I missed that!

Full-screen is then the only suggestion remaining from my side.

**Comment by jderose9** [comment]
Round of applause for @charlesg99 ! Seems to be working well for me. If anyone would like to help with testing the latest master, that would be great.

**Comment by vivaeltopo** [comment]
Awesome work. Did not find any problems with 3.28

**Comment by ddnexus** [comment]
The problem I have with the Hide Top Bar are the following 2:

1. it makes the peeking window feature practically unusable, since the preview thumbnails disappear as soon as you move on them (i.e. out of the top bar) I cannot find any settings to mitigate that.

2. it requires to restart the shell after a suspend, because the bar hides itself after a fraction of a second it appeared (i.e. doesn't stay visible)

**Comment by SolarLiner** [comment]
@ddnexus This is why the Intellihide feature was developped. It's not released yet, but will soon be.

**Comment by ddnexus** [comment]
I didn't know that! Great! I cannot wait to try it. Is it available in any branch to try?

**Comment by nunocastromartins** [comment]
I believe it is available on the master branch; simply not released to GNOME Shell Extensions.

**Comment by ddnexus** [comment]
Yeah! After I wrote the post I realized it, and it is installed now It works! Thanks!
