### ISSUE TITLE
Quick <Super>+0-9 App Launchers

### ISSUE THREAD

**Issue by alex285** [jderose9/dash-to-panel#45]
Similar to https://github.com/micheleg/dash-to-dock/pull/360 and Unity launcher

**Comment by amankhoza** [comment]
Have you tried the AppKeys Gnome extension, works great with Dash to panel:

**Comment by franglais125** [comment]
Here is an implementation for this request.
https://github.com/franglais125/dash-to-panel/tree/hotkeys

@jderose9 If you like it, I can open a PR. I've implemented this for dash-to-dock as well.

Cheers

**Comment by alex285** [comment]
@amankhoza nop, I didnt know that extension. But it is very core and required feature, I think it would be better if it was inside Dash To Panel, if possible!

**Comment by jderose9** [comment]
@franglais125 Great, thanks! I'd be happy to accept a PR. Would you mind if the default is off, though? I don't want to override user keybindings without them taking explicit action (I personally use Super+Num to switch workspaces currently). Also, I see the keybindings in the settings schema but no UI for it. Did you forget to merge that or just planning for users to alter it via dconf? Thanks again.

**Comment by franglais125** [comment]
I'll switch it to off then!

As for the keybindings, I kept them "behind the scenes", as usually in dash-to-dock he philosophy is not to over-complicate the settings. We could add a second layer of options behind a button for this I guess.

For some reason, it is not possible to configure the keybindings via dconf. Maybe due to the fact that they are string-vectors, not just text.

I'll try to work on configurability, but I can't promise anything soon!

**Comment by jderose9** [comment]
This was completed in #48. Thanks @franglais125!
