### ISSUE TITLE
Move the extensions to the right 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jderose9/dash-to-panel#5]
It should be great to have the extensions on the right
![capture d ecran de 2017-01-08 15-47-55](https://cloud.githubusercontent.com/assets/7660997/21750711/d8e07342-d5b9-11e6-871e-d1d40adb382f.png)
If you don't want to do this, i can create an extension to change it position :)

**Comment by jderose9** [comment]
Hi.. can you explain a little better? I'm not sure what you are looking for. What exactly do you want to move to the right? Thanks!

**Comment by bil-elmoussaoui** [comment]
The tray icons "panel", it's more "correct" to have it close to have it on right then on left

**Comment by jderose9** [comment]
Oh I see. I think this makes more sense as a separate extension as many people may want to move the legacy tray regardless of whether they are using this extension.

Let me know if you get this working as it's something I wouldn't mind to check out! Currently I am using Top Icons Plus to move them into the main panel itself.

Thanks for the feedback!

**Comment by bil-elmoussaoui** [comment]
I will try to create an extension to hide/show and change it position ;) 
Closing! i will let you know once it's done!

**Comment by jderose9** [comment]
Awesome! Good luck!

**Comment by cra0zy** [comment]
There is also https://github.com/rgcjonas/gnome-shell-extension-appindicator which you can run side by side with Top Icons Plus. That extension, tho a bit dead ATM, will actually create a proper gnome shell extension item for each indicator instead of just copying the item like Top Icons Plus, but it will not work on all indicators, it works on Steam, but does not work on Skype and Chrome.
