### ISSUE TITLE
Cycle windows should focus in LRU order

### ISSUE THREAD

**Issue by jhasse** [jderose9/dash-to-panel#53]
* App A
  * window 1
  * window 2
* App B
  * window 3

Clicking two times on A brings window 2 to the front. Clicking on B switches to window 3. Now clicking on A again brings windows 1 again, but I think it should be window 2 (the one which was last recently used).

**Comment by jderose9** [comment]
Yes, I agree. Thanks for the feedback!

**Comment by smithfred** [comment]
I agree about LRU behaviour, but if there's an easy partial fix in the interim so that clicking on the icon of an unfocused application always shows the last-used window initially, that would be very useful in the interim for the simple use-case of switching back and forth between two applications where one has more than one window, which I'd almost call a bug at the moment rather than an enhancement.

Fantastic extension by the way, first dash replacement that I've actually wanted to keep using after more than a day or two!

**Comment by jderose9** [comment]
I pulled in the behavior from dash-to-dock (and updated it to work with the cycle+min option). If you want to check it out, it's in the `master` branch. Thanks!
