### ISSUE TITLE
panel size incorrect after reboot/logout

### ISSUE THREAD

**Issue by jekohk** [jderose9/dash-to-panel#67]
Upon first logging, regardless of what I set the panel size to in the extension's settings, the panel displays much too small- see screenshot below.

The quick fix seems to be disabling/re-enabling the extension at which point the panel comes back scaled correctly, however obviously this is a bit of a pain having to do that each time I log in.

For reference, I am running at 2560x1440 resolution with GNOME's scaling factor at 2.

Let me know if there is any other info you need to help debug this.

![screenshot from 2017-02-13 11-20-00](https://cloud.githubusercontent.com/assets/12895773/22891892/c99e0700-f1de-11e6-91cc-cfae1399b75f.png)

**Comment by jderose9** [comment]
Hi there! thanks so much for reporting this. I believe this issue was already reported and fixed in #57.

It will be in the v6 release which is still awaiting approval on gnome.org. But, you can get the code directly from github if you would like (though you will want to remove it manually when it is available on gnome.org to get automatic update notifications again).

**Comment by jekohk** [comment]
Ah, now I feel stupid! I will check out the dev branch. Thanks!

**Comment by jderose9** [comment]
No need to feel stupid! Thanks for your time. Let me know if it doesn't resolve the issue!
