### ISSUE TITLE
System tray not registering clicks?

### ISSUE THREAD

**Issue by tgharib** [jderose9/dash-to-panel#73]
It seems I have to click 20+ times to register a click on an application icon in the tray. This bug doesn't seem to be reproduced when dash to panel is disabled.

**Comment by jderose9** [comment]
When you say tray, you mean the application launcher icons or the right hand side widgets like the clock and power menu?

This happens always for you, or just occasionally?

**Comment by tgharib** [comment]
I mean the application launcher icons. The clock and power menu work great.

It always happens for me. It might be a corrupt install if other people are not experiencing this issue. I'll do a fresh install in a VM and see if I can reproduce it.

**Comment by jderose9** [comment]
I haven't heard any other reports of this. Do you have any sort of software keyboard or other overlays that might be capturing the clicks? Are you using a touch device? What distro and gnome version are you running? Thanks!

**Comment by tgharib** [comment]
I don't use any software keyboard or any overlays. I'm using a mouse (no touch device) on a desktop. I'm using Manjaro and Gnome 3.22.2. After some further investigation, I've noticed that it only happens for some programs. Applications such as pCloud and KeepassXC seem to have this issue but it seems Steam always works.

Actually, I decided to some more investigation while I was writing this comment and I think I've found a way to reliably reproduce this issue.

Here is my desktop:

![desktop](https://cloud.githubusercontent.com/assets/6457015/23564054/2e3246b8-0017-11e7-833a-fa7db6155d4e.png)

And here is the system tray with a horizontal red line:

![clipped](https://cloud.githubusercontent.com/assets/6457015/23564053/2e3195f6-0017-11e7-8aad-133f500c4259.png)

It seems that for all the system tray icons (steam, pCloud, KeepassXC, etc), if I click above the horizontal red line, it works. If I click below the line, it doesn't work.

**Comment by jderose9** [comment]
Yeah something is definitely goofy. Your steam icon is top alighned and the icon to the left is stretched. They should be the same size and centered. It seems like you've got something going on with the panel that is atypical causing this behavior when it's resized. Here's some stuff to try:

1. Changes themes. If you are using a custom theme, try the default (Can you pick the gnome default theme in manjaro rather than their customized one?). Otherwise, try a popular theme like Arc.
2. Set all the sliders on the 3rd tab ("Fine-Tune" or "Appearance" depending on what version you are using) all the way to the left so that this extension isn't applying any additional styles to those icons. If they are already on the left, try adjusting the tray font size to something a good bit smaller than the panel height to see if there is any improvement.
3. Disable all other extensions and see if it is to ensure it is caused by this extension.

**Comment by tgharib** [comment]
Following your advice, I've found the culprit was the "Topicons" extension. It was deprecated and replaced by a new extension called "Topicons plus" since Gnome 3.14 and I wasn't aware of that. The funny thing is that the tray icons seemed to work with "Dash to Dock" so I assumed it was this extension (since it was the new variable). I apologize for wasting your time with an unrelated legacy extension bug.

**Comment by jderose9** [comment]
Awesome, glad you got it worked out!
