### ISSUE TITLE
Transparent icons get squashed

### ISSUE THREAD

**Issue by Anti-Ultimate** [jderose9/dash-to-panel#87]
I'm making AppImages, and I noticed that when a AppImage is using a transparent icon, the icon gets squashed.

You can download the AppImage from here:
https://drive.google.com/open?id=0B-tFnZC4LvDuMFJNZHZYcGdrYzg

It seems to look for the nearest pixel and uses that for the dimensions instead of just using the image's dimensions.

https://imgur.com/a/FkNUu

**Comment by jderose9** [comment]
Hi there! Do you mind to post a screenshot so that those reading don't have to execute a binary to see the issue?

**Comment by Anti-Ultimate** [comment]
https://imgur.com/a/FkNUu

**Comment by jderose9** [comment]
Oh, so it is getting stretched vertically, correct?

Could you verify that this is specific to this extension? If you disable this extension, do you see the same behavior when seeing the icon on the left side dash after opening the Activities overview?

I'm making a speculation that your svg is being used and that gnome is ignoring the viewBox for scalable icons and looking only at the path. Perhaps you could try providing .png in all of the sizes needed rather than just 48px? They are:

16, 22, 24, 32, 48, 64, 96, 128

**Comment by Anti-Ultimate** [comment]
After further inspection, it seems to be related to GNOME. I don't know why this happens, the AppImage uses the .png file, which I manually copied into the script used to create this AppImage

**Comment by jderose9** [comment]
I'm going to go ahead and close this one since it isn't specific to this extension, though I think you can work around your issue by providing png's at every size in the corrent place under usr/share/icons folder structure.
