### ISSUE TITLE
no preview when mouse hovers over the LibreOffice Calc icon

### ISSUE THREAD

**Issue by wolfv6** [jderose9/dash-to-panel#88]
Normally, hovering mouse over an application icon, on top panel, will preview any open windows of the application.
It works for LibreOffice Writer icon, and all my other open applications.
But there's no preview when my mouse hovers over the LibreOffice Calc icon.
The open LibreOffice Calc window is previewed in Activities Overview as expected.

I am on Fedora 25, Gnome 3.22.2, Dash-to-Panel v6.

BTW - dash-to-panel makes the desktop nice.

**Comment by jderose9** [comment]
My previews show up, however if I open two different LibreOffice applications, the icon doesn't appear in the dash for the 2nd application until I open or close some other application. Is that what you are seeing? Unfortunately, this happens even without this extension installed, so I don't think the issue is related to dash-to-panel.

![screenshot from 2017-03-11 21-28-22](https://cloud.githubusercontent.com/assets/2118702/23828521/1f569d74-06a2-11e7-8957-844f89c077f0.png)

**Comment by wolfv6** [comment]
I often have multiple spreadsheets open, but I rarely open any other LibreOffice application.
I didn't have any problem with multiple spreadsheets open before installing dash-to-app.

**Comment by jderose9** [comment]
So when you hover over the icon no popup comes up? Or the popup comes up and is empty? Or the Calc icon doesn't show up at all? Is there some way you can take a screenshot?

**Comment by wolfv6** [comment]
When I hover over the Calc icon, the "LibreOffice Calc" tool tip appears (see screenshot).
When I click on the Calc icon, it opens a fresh Calc in a new window.
![screenshot_dash-to-panel_calc_nobackup](https://cloud.githubusercontent.com/assets/1121166/23835536/aa3ebb1a-072e-11e7-8f55-ddab0d5cf05b.png)

**Comment by jderose9** [comment]
I'm guessing something is wrong with your .desktop file. If you disable this extension, and open the Activities Overview, do you see the Calc underlined as a running application in the left side dash (favorites bar)?

**Comment by wolfv6** [comment]
With LibreOffice Calc open, dash-to-panel OFF, and Activities Overview open, left side dash contains the Calc icon, without underline or dot.

With LibreOffice Calc open, dash-to-panel ON, top panel contains the Calc icon, without underline or dot.

**Comment by jderose9** [comment]
Ok, so your issue is not caused by this extension. Gnome does not understand that the running window is the same application as the Calc in your favorites.

Here's some stuff to try...
1. Try unfavoriting and refavoriting Calc
2. Perhaps the issue is in your /usr/share/applications/libreoffice-calc.desktop file or something has changed since you favorited it? Here's mine:
http://pastebin.com/STznKF86
3. Or perhaps you've overridden the package provided libreoffice-calc.desktop with an invalid one in ~/.local/share/applications?

**Comment by wolfv6** [comment]
Thanks for your help jderose9.  Unfortunally still no Calc preveiw on hover.  Maybe it will work on my next Fedora reinstall.
This what I tried:
    1. unfavoriting and refavoriting Calc: no change in behavior
    2. yours and mine libreoffice-calc.desktop files are identical (I ran diff)
    3. there is no Calc desktop file in my ~/.local/share/applications

**Comment by bil-elmoussaoui** [comment]
@wolfv6 You must open a bug report for the packagers of libreoffice in your distro. But anyway, you can use this to fix your issue https://github.com/bil-elmoussaoui/StartupWMClassFixer see the readme on how to do so

**Comment by wolfv6** [comment]
Thanks bil-elmoussaoui.
I submitted a bug report at https://bugzilla.redhat.com/show_bug.cgi?id=1434530
